/* ---------- CİLT ATLASI · içerik (24 alt sayfa) ----------
   Kurallar: yalnızca salonun gerçek medyası; önce/sonra yalnızca gerçek çiftlerle; fiyat yalnızca PLANS.cilt'ten
   (CRM); ihtiyaç rehberi (İ) sayfaları başka bakımın fiyatını kendi fiyatıymış gibi göstermez; sonuç vaadi yok. */
var CM={
 led:{v:"cilt-led-dongu",alt:"LED ışık terapisi: yüzde yeşil, mavi ve kırmızı ışık"},
 kubbe:{v:"cilt-kubbe",alt:"LED kubbe altında cilt bakımı"},
 saten:{v:"cilt-saten",alt:"Saten yüz germe başlığı yanak ve şakakta"},
 satenY:{v:"cilt-saten-yakin",alt:"Saten yüz germe başlığı alın ve göz çevresinde"},
 analiz:{v:"cilt-analiz",alt:"Büyüteçli lamba altında cilt analizi"},
 masaj:{v:"cilt-masaj",alt:"Eldivenli ellerle yüz masajı"},
 kopuk:{v:"cilt-kopuk",alt:"Temizleme süngeri ve köpük"},
 komedon:{v:"cilt-komedon",alt:"Steril uçla siyah nokta temizliği"},
 darsonval:{v:"cilt-darsonval",alt:"Darsonval elektrodu akneli yanakta"},
 yuz1:{pair:"yuz-cift-1",s:480,alt:"Yüz bakımı: kızarıklık ve ton farkı"},
 akne1:{pair:"akne-cift-1",s:800,alt:"Akne bakımı"},
 akne2:{pair:"akne-cift-2",s:800,alt:"Akne bakımı, ikinci danışan"}
};
var CA_GROUPS=[["akne","Sivilce, gözenek, siyah nokta"],["isilti","Işıltı ve nem"],["ton","Leke ve ton"],["yas","Sıkılık ve çizgi görünümü"],["vucut","Vücut ve dudak"],["rehber","Başlarken"]];
var CA_SEANS=[
 {m:"analiz",w:"Adım 1",k:"Önce bakarız",h:"Büyüteçli lambanın altında.",p:"Gözenek, nem, hassasiyet ve şikâyetiniz birlikte değerlendirilir. Bakımın geri kalanı bu bakışa göre şekillenir."},
 {m:"kopuk",w:"Adım 2",k:"Arındırma",h:"Cildinize uygun köpükle.",p:"Makyaj, gün boyu biriken kir ve yağ yumuşak bir süngerle alınır."},
 {m:"komedon",w:"Adım 3",k:"Siyah nokta",h:"Gerekiyorsa tek tek.",p:"Siyah noktalar steril uçla, cildi zorlamadan temizlenir. Hassas bölgelerde daha nazik ilerlenir."},
 {m:"masaj",w:"Adım 4",k:"Masaj",h:"Ellerimizle, acele etmeden.",p:"Yüz masajı bakımın en sevilen anıdır; kan dolaşımı canlanır, yüz gevşer."},
 {m:"led",w:"Adım 5",k:"Işık",h:"LED ile kapanış.",p:"Bakımın sonunda LED ışık terapisiyle dinlenirsiniz. Işık rengini uzmanımız cildinize göre seçer."}];
var CP={
"cilt-bakimi-fiyatlari":{t:"Cilt bakımı fiyatları",code:"cfiyat",kind:"I",grp:"rehber",h1:["Cilt bakımı","fiyatları"],
 lede:"Her bakımın süresi ve fiyatı tek bakışta.",hero:"kubbe",heroNote:"LED kubbe, salonumuzda çekildi. Fiyatlar randevu sistemimizdeki aktif menüden.",
 scene:{type:"menu"},
 acts:[{m:"kubbe",k:"Nereden başlamalı?",h:"Yarım saatten iki saate.",p:"Kısa bir arada cilt temizliği, ilk kez geliyorsanız klasik bakım, belirli bir derdiniz varsa ana bakımlar."},
   {m:"analiz",k:"Fiyat neye göre?",h:"Bakımın süresine ve adımlarına göre.",p:"Ana bakımlar iki saat sürer ve cihazla desteklenir. Ara bakımlar daha kısa ve daha sadedir."},
   {m:"led",k:"Paketler",h:"Ana bakımlarda 5 seans.",p:"5 seanslık paket, tek seans fiyatının 4,5 katıdır. Hangi bakımın size uygun olduğunu ilk seansta birlikte konuşuruz."}],
 faq:[["Fiyatlar güncel mi?","Bu sayfadaki fiyatlar randevu sistemimizdeki aktif menüden alınır. Kesin fiyatı randevu onayında WhatsApp'tan da iletiriz."],["Ödemeyi nasıl yapıyorum?","Ödeme bakım günü salonda yapılır."]],
 route:["klasik-cilt-bakimi","cilt-temizligi","akne-bakimi","hollywood-bakimi"]},
"klasik-cilt-bakimi":{t:"Klasik cilt bakımı",code:"cklasik",kind:"H",opt:"klasik",grp:"rehber",h1:["Klasik","cilt bakımı"],
 lede:"Doksan dakika, beş adım, tertemiz bir yüz.",hero:"analiz",heroNote:"Büyüteçli lamba altında cilt analizi, salonumuzda çekildi.",
 actsHead:["Bir bakımın içinden","90 dakika, adım adım."],acts:"seans",
 proof:["yuz1"],quote:"Burcu Ö.",
 faq:[["İlk kez yaptıracağım, uygun mu?","Evet. Çoğu danışanımız ilk bakımına klasik cilt bakımıyla başlar."],["Bakımdan sonra kızarıklık olur mu?","Siyah nokta temizliği yapılan bölgelerde kısa süreli hafif kızarıklık olabilir; genellikle aynı gün içinde geçer."],["Ne sıklıkla gelmeliyim?","Cildinize göre değişir; uzmanımız bakım sonunda önerir."]],
 route:["cilt-temizligi","akne-bakimi","paris-isiltisi-bakimi"]},
"cilt-temizligi":{t:"Cilt temizliği",code:"ctemiz",kind:"H",opt:"temizlik",grp:"akne",h1:["Cilt","temizliği"],
 lede:"Yarım saatte arınmış, nefes alan bir cilt.",hero:"kopuk",heroNote:"Temizleme köpüğü, salonumuzda çekildi.",
 acts:[{m:"analiz",k:"Aynada",h:"Burun kenarında siyah noktalar mı?",p:"Gözenekler kirle dolunca cilt mat ve pürüzlü görünür. Kısa ama doğru bir temizlik çoğu zaman fark yaratır."},
   {m:"kopuk",k:"Koltukta",h:"Önce köpük, sonra buhar.",p:"Cilt yumuşatılır, gözenekler temizliğe hazırlanır."},
   {m:"komedon",k:"Siyah nokta",h:"Steril uçla, tek tek.",p:"Siyah noktalar cildi zorlamadan alınır. Sonrasında yatıştırıcı bir bakımla kapatılır."},
   {m:"led",k:"Sonra",h:"Hafif, temiz, ferah.",p:"Temizlenen bölgelerdeki hafif kızarıklık kısa sürede geçer. Aynı gün işinize dönebilirsiniz."}],
 proof:["yuz1"],quote:"Berke S.",
 faq:[["Ne kadar sürer?","30 dakika."],["Klasik bakımdan farkı ne?","Cilt temizliği arındırmaya odaklanır. Klasik bakımda buna masaj, maske ve LED ile kapanış eklenir ve 90 dakika sürer."]],
 route:["klasik-cilt-bakimi","akne-bakimi"]},
"akne-bakimi":{t:"Akne bakımı",code:"cakne",kind:"H",opt:"akne",grp:"akne",h1:["Akne","bakımı"],
 lede:"Sivilceye eğilimli cilt için iki saatlik özenli bakım.",hero:"darsonval",heroNote:"Darsonval uygulaması, salonumuzda çekildi.",
 acts:[{m:"akne1",k:"Aynada",h:"Her sabah yeni bir sivilce.",p:"Akneye eğilimli cilt hem görünüşle hem moralle ilgilidir. Önce dinleriz: ne zaman başladı, neler denediniz?"},
   {m:"analiz",k:"Önce bakarız",h:"Hangi bölge, hangi tip?",p:"Siyah nokta, iltihaplı sivilce ve kızarıklık ayrı ayrı değerlendirilir. Bakım buna göre kurulur."},
   {m:"komedon",k:"Temizlik",h:"Gözenekleri boşaltırız.",p:"Siyah noktalar steril uçla temizlenir; iltihaplı bölgelere dokunulmaz."},
   {m:"darsonval",k:"Işıltılı elektrot",h:"Darsonval ile.",p:"Turuncu ışıyan cam elektrot cilt üzerinde gezdirilir. Bakımın yatıştırıcı adımlarından biridir."},
   {m:"akne2",k:"Sonra",h:"Sabır ve düzen.",p:"Akne bakımında sonuç tek seansta değil, düzenli bakımla gelir. Görseller iki danışanımızın gerçek önce/sonrasıdır; her cilt farklıdır."}],
 dark:{m:"darsonval",k:"Seansın içinden",h:"Işığın <em>sakinliği</em>.",p:"Darsonval elektrodu akneli yanakta: tek çekim, kurgusuz, salonumuzda."},
 proof:["akne1","akne2"],quote:"Berke S.",
 faq:[["Kaç seans gerekir?","Cildinize göre değişir. Ana bakımların 5 seanslık paketleri vardır; uzmanımız ilk seansta önerir."],["Evde ne yapmalıyım?","Bakım sonunda cildinize uygun ev bakımı önerilir."],["Bu bir tedavi mi?","Hayır, profesyonel bir cilt bakımıdır. Yoğun ve ağrılı aknede dermatoloji muayenesi öneririz."]],
 route:["cilt-temizligi","klasik-cilt-bakimi","hassas-cilt"]},
"cilt-yenileme":{t:"Cilt yenileme",code:"cyenile",kind:"H",opt:"yenileme",grp:"ton",h1:["Cilt","yenileme"],
 lede:"Mat ve yorgun görünen cilde yeniden ışık.",hero:"kubbe",heroNote:"LED kubbe altında bakım, salonumuzda çekildi.",
 acts:[{m:"yuz1",k:"Aynada",h:"Ton eşitsiz, cilt yorgun.",p:"Kızarıklık, lekelenme ve matlık birlikte olunca yüz olduğundan yorgun görünür."},
   {m:"analiz",k:"Önce bakarız",h:"Hangi bölge, ne kadar?",p:"Yenileme tüm yüze ya da belirli bölgelere uygulanabilir. Bölgeyi birlikte seçeriz."},
   {m:"kubbe",k:"Koltukta",h:"Yenileme ve ışık.",p:"Bakım LED ışık terapisiyle tamamlanır."},
   {m:"yuz1",k:"Sonra",h:"Daha eşit, daha aydınlık görünüm.",p:"Görsel, salonumuzda bakım yaptıran bir danışanımızın gerçek önce/sonrasıdır. Sonuç kişiden kişiye değişir."}],
 pick:{h:"Kaç bölge?",o:[["1","1 bölge","3.500 TL"],["2","2 bölge","4.000 TL"],["3","Tüm yüz","6.000 TL"]],note:"Bölge fiyatları randevu sistemimizdeki menüden. Kesin fiyat cildinize bakıldıktan sonra onaylanır.",msg:"Merhaba, cilt yenileme bakımı ({x}) için uygun bir saat var mı?"},
 proof:["yuz1"],
 faq:[["Kaç seans önerirsiniz?","Ana bakımların 5 seanslık paketleri vardır; ihtiyacınızı ilk seansta birlikte belirleriz."],["Güneşe çıkabilir miyim?","Bakım sonrası güneş koruyucu kullanmanızı öneririz."]],
 route:["ton-esitleme","leke-bakimi","hollywood-bakimi"]},
"ton-esitleme":{t:"Ton eşitleme",code:"cton",kind:"H",opt:"ton",from:4500,grp:"ton",h1:["Ton","eşitleme"],
 lede:"Kızarıklık ve renk farkı için hedefli bakım.",hero:"led",heroNote:"LED ışık terapisi, salonumuzda çekildi.",
 acts:[{m:"yuz1",k:"Aynada",h:"Yanakta kızarıklık, alında renk farkı.",p:"Ton farkı fondötenle kapatılır ama cilt hep yorgun görünür."},
   {m:"analiz",k:"Önce bakarız",h:"Alanı ölçeriz.",p:"Bakım, ton farkının bulunduğu alanın büyüklüğüne göre planlanır."},
   {m:"led",k:"Koltukta",h:"Bakım ve ışık.",p:"Ton eşitleyici bakım LED ışık terapisiyle tamamlanır."},
   {m:"yuz1",k:"Sonra",h:"Daha eşit görünen bir ton.",p:"Görsel gerçek bir danışanımızın bakım öncesi ve sonrasıdır. Sonuç kişiden kişiye değişir."}],
 pick:{h:"Alan ne kadar?",o:[["kucuk","Küçük alan","4.500 TL"],["orta","Orta alan","5.500 TL"],["genis","Geniş alan","6.500 TL"]],note:"Alan fiyatları randevu sistemimizdeki menüden. Alanı uzmanımız cildinize bakarak kesinleştirir.",msg:"Merhaba, ton eşitleme ({x}) için uygun bir saat var mı?"},
 proof:["yuz1"],
 faq:[["Lekeler tamamen gider mi?","Söz veremeyiz; amaç tonu daha eşit göstermektir. Düzenli bakım ve güneş koruması fark yaratır."]],
 route:["leke-bakimi","cilt-yenileme","cilt-kararma-bakimi"]},
"saten-yuz-germe":{t:"Saten yüz germe",code:"csaten",kind:"H",opt:"saten",grp:"yas",h1:["Saten","yüz germe"],
 lede:"İğnesiz, altmış dakikalık sıkı görünüm bakımı.",hero:"saten",heroNote:"Saten yüz germe başlığı, salonumuzda çekildi.",
 film:{k:"Seansın içinden",h:"Başlık yüzde nasıl gezer?",p:"Aşağı kaydırın: cihazın ekranından alın ve göz çevresine, tek bir seanstan kesitler."},
 acts:[{m:"satenY",k:"Aynada",h:"Göz kenarında çizgiler, yanakta gevşeklik.",p:"Yorgunluk önce yüzün çerçevesinde görünür."},
   {m:"saten",k:"Koltukta",h:"Başlık yanaktan şakağa.",p:"Isıtan başlık cilt üzerinde yavaşça gezdirilir. Uygulama sırasında hafif bir sıcaklık hissedilir."},
   {m:"satenY",k:"Göz çevresi",h:"Alında ve göz kenarında.",p:"İnce bölgelerde başlık daha küçük hareketlerle çalışır."},
   {m:"led",k:"Sonra",h:"Aynı gün hayatınıza dönün.",p:"İğne yok, iz yok. Daha sıkı bir görünüm için seanslar uzmanımızın önerisiyle planlanır."}],
 faq:[["Acıtır mı?","Hafif bir sıcaklık hissedilir; çoğu danışanımız rahatlatıcı bulur."],["Ne kadar sürer?","60 dakika."]],
 route:["anti-aging-bakimi","goz-cevresi-bakimi","cilt-inceltme"]},
"anti-aging-bakimi":{t:"Anti aging bakımı",code:"caging",kind:"I",grp:"yas",h1:["Anti aging","bakımı"],
 lede:"Çizgi ve sıkılık için hangi bakım? Doğru yolu birlikte seçelim.",hero:"satenY",heroNote:"Saten yüz germe uygulaması, salonumuzda çekildi.",
 acts:[{m:"satenY",k:"Aynada",h:"Gülerken kalan çizgiler.",p:"Göz kenarı, alın ve çene hattı zamanla değişir. Her biri farklı bir yaklaşım ister."},
   {m:"analiz",k:"Önce bakarız",h:"Hangi bölge, hangi ihtiyaç?",p:"Sıkılık mı, nem mi, ton mu? Önceliği belirleyip doğru bakıma yönlendiririz."},
   {m:"saten",k:"Yol 1",h:"Saten yüz germe.",p:"Sıkı görünüm için ısıtan başlıkla 60 dakikalık bakım."},
   {m:"kubbe",k:"Yol 2",h:"Cilt yenileme.",p:"Matlık ve ton için bölgesel yenileme bakımı."}],
 faq:[["Bu sayfanın fiyatı ne?","Anti aging bir ihtiyaç başlığıdır; fiyat seçeceğiniz bakıma göre değişir. Aşağıdaki bakımların fiyatları kendi sayfalarında."]],
 route:["saten-yuz-germe","cilt-yenileme","goz-cevresi-bakimi"],shoot:true},
"goz-cevresi-bakimi":{t:"Göz çevresi bakımı",code:"cgoz",kind:"I",grp:"yas",h1:["Göz çevresi","bakımı"],
 lede:"Yüzün en ince derisine en nazik dokunuş.",hero:"satenY",heroNote:"Göz çevresinde saten başlık, salonumuzda çekildi.",
 acts:[{m:"satenY",k:"Aynada",h:"Kaz ayağı, yorgun bakış.",p:"Göz çevresi yüzün en ince derisidir; ilk yorgunluk burada görünür."},
   {m:"analiz",k:"Önce bakarız",h:"Çizgi mi, nem mi?",p:"İhtiyaca göre saten yüz germe ya da klasik bakım önerilir."},
   {m:"saten",k:"Yol",h:"Küçük hareketlerle.",p:"Saten başlık göz kenarında daha küçük ve yavaş hareketlerle çalışır."}],
 faq:[["Göz çevresi için ayrı bir fiyat var mı?","Göz çevresi bir ihtiyaç başlığıdır; fiyat seçilen bakıma göredir."]],
 route:["saten-yuz-germe","klasik-cilt-bakimi"],shoot:true},
"cilt-analizi":{t:"Cilt analizi",code:"canaliz",kind:"I",grp:"rehber",h1:["Cilt","analizi"],
 lede:"Her iyi bakım, doğru bir bakışla başlar.",hero:"analiz",heroNote:"Büyüteçli lamba altında, salonumuzda çekildi.",
 scene:{type:"map"},
 acts:[{m:"analiz",k:"Lambanın altında",h:"Gözle görmediğimizi büyüteçle.",p:"Gözenek, siyah nokta, kuruluk ve kızarıklık büyüteçli lamba altında değerlendirilir."},
   {m:"masaj",k:"Dokunarak",h:"Cildin dokusu.",p:"Nem ve esneklik dokunarak anlaşılır."},
   {m:"led",k:"Sonra",h:"Size uygun yol.",p:"Analiz ön görüşmedir; ardından ihtiyacınıza uygun bakım önerilir."}],
 faq:[["Analiz ücretli mi?","Cilt analizi bakımın başında yapılır. Yalnızca görüşme için gelmek isterseniz WhatsApp'tan yazın."]],
 route:["klasik-cilt-bakimi","akne-bakimi","cilt-yenileme","saten-yuz-germe"]},
"yuz-bakimi":{t:"Yüz bakımı",code:"cyuz",kind:"I",grp:"rehber",h1:["Yüz","bakımı"],
 lede:"Yüzünüz için dört yol: hangisi size göre?",hero:"masaj",heroNote:"Yüz masajı, salonumuzda çekildi.",
 acts:[{m:"yuz1",k:"Aynada",h:"Yüzünüz ne anlatıyor?",p:"Kızarıklık, matlık, sivilce ya da sadece yorgunluk. Her biri farklı bir bakıma işaret eder."},
   {m:"analiz",k:"Önce bakarız",h:"Doğru yol için.",p:"Kısa bir analizle başlarız."},
   {m:"masaj",k:"Koltukta",h:"Ellerimizle.",p:"Hangi bakımı seçerseniz seçin, masaj ve özen her bakımın parçasıdır."},
   {m:"yuz1",k:"Sonra",h:"Gerçek bir danışanımız.",p:"Görsel salonumuzda bakım yaptıran bir danışanımızın gerçek önce/sonrasıdır."}],
 proof:["yuz1"],
 route:["klasik-cilt-bakimi","cilt-temizligi","paris-isiltisi-bakimi","cilt-yenileme"]},
"leke-bakimi":{t:"Leke bakımı",code:"cleke",kind:"H",opt:"leke",grp:"ton",h1:["Leke","bakımı"],
 lede:"Güneş ve zamanın bıraktığı izler için iki saat.",hero:"led",heroNote:"LED ışık terapisi, salonumuzda çekildi. Leke bakımına özel çekimimiz hazırlanıyor.",
 acts:[{m:"analiz",k:"Aynada",h:"Yanakta, alında koyu izler.",p:"Leke görünümü güneşle, hormonlarla ya da sivilce sonrası oluşabilir. Hangisi olduğunu önce anlamamız gerekir."},
   {m:"kopuk",k:"Hazırlık",h:"Arındırma.",p:"Bakım temiz ve hazırlanmış bir ciltte başlar."},
   {m:"led",k:"Koltukta",h:"Bakım ve ışık.",p:"Leke bakımı LED ışık terapisiyle tamamlanır."},
   {m:"masaj",k:"Sonra",h:"Güneş koruması şart.",p:"Leke bakımında sonuç düzenli bakım ve güneş korumasıyla gelir. Kesin sonuç vaat etmeyiz."}],
 faq:[["Kaç seans?","Ana bakımların 5 seanslık paketleri vardır; ihtiyacı ilk seansta birlikte belirleriz."],["Yazın yaptırabilir miyim?","Uzmanımız mevsime ve cildinize göre önerir; güneş koruyucu her mevsim gerekir."]],
 route:["ton-esitleme","cilt-yenileme","cilt-kararma-bakimi"],shoot:true},
"hollywood-bakimi":{t:"Hollywood bakımı",code:"cholly",kind:"H",opt:"hollywood",grp:"isilti",h1:["Hollywood","bakımı"],
 lede:"Özel bir günden önce iki saatlik ışıltı.",hero:"kubbe",heroNote:"LED kubbe, salonumuzda çekildi. Hollywood bakımına özel çekimimiz hazırlanıyor.",
 scene:{type:"duel",a:"hollywood-bakimi",b:"paris-isiltisi-bakimi"},
 acts:[{m:"masaj",k:"Aynada",h:"Düğün, nişan, fotoğraf günü.",p:"Önemli bir günden önce cildin dinlenmiş ve ışıltılı görünmesi istenir."},
   {m:"kopuk",k:"Hazırlık",h:"Derin arındırma.",p:"Cilt temizlenir ve bakıma hazırlanır."},
   {m:"kubbe",k:"Koltukta",h:"Maske ve ışık.",p:"Bakım LED kubbe altında tamamlanır."},
   {m:"led",k:"Sonra",h:"Işıltılı görünüm.",p:"Özel günden birkaç gün önce planlamanızı öneririz."}],
 faq:[["Paris ışıltısından farkı ne?","İkisi de 120 dakikalık ışıltı bakımıdır; ürün ve adımları farklıdır. Hangisinin cildinize uygun olduğunu uzmanımız cildinize bakarak söyler."]],
 route:["paris-isiltisi-bakimi","klasik-cilt-bakimi"],shoot:true},
"paris-isiltisi-bakimi":{t:"Paris ışıltısı",code:"cparis",kind:"H",opt:"paris",grp:"isilti",h1:["Paris","ışıltısı"],
 lede:"Mat cilde iki saatte canlı bir parıltı.",hero:"led",heroNote:"LED ışık terapisi, salonumuzda çekildi. Paris ışıltısına özel çekimimiz hazırlanıyor.",
 scene:{type:"duel",a:"paris-isiltisi-bakimi",b:"hollywood-bakimi"},
 acts:[{m:"analiz",k:"Aynada",h:"Mat, susuz, yorgun.",p:"Kış, stres ve uykusuzluk cildin parlaklığını alır."},
   {m:"kopuk",k:"Hazırlık",h:"Arındırma.",p:"Cilt temizlenir ve bakıma hazırlanır."},
   {m:"masaj",k:"Koltukta",h:"Bakım ve masaj.",p:"Işıltı bakımı yüz masajıyla devam eder."},
   {m:"led",k:"Sonra",h:"Canlı görünüm.",p:"LED ışık terapisiyle kapanış."}],
 faq:[["Hollywood bakımından farkı ne?","İkisi de 120 dakikalık ışıltı bakımıdır; ürün ve adımları farklıdır. Uzmanımız cildinize bakarak önerir."]],
 route:["hollywood-bakimi","hydra-elite"],shoot:true},
"dermabrazyon":{t:"Dermabrazyon",code:"cderma",kind:"H",opt:"derma",grp:"isilti",h1:["Dermabrazyon","yüz bakımı"],
 lede:"Pürüzlü dokuya doksan dakikalık yenilenme.",hero:"kubbe",heroNote:"LED kubbe, salonumuzda çekildi. Dermabrazyon cihazımızın çekimi hazırlanıyor.",
 acts:[{m:"analiz",k:"Aynada",h:"Gözenekler belirgin, doku pürüzlü.",p:"Makyaj oturmaz, cilt dokunca pürüzlü hissedilir."},
   {m:"kopuk",k:"Hazırlık",h:"Arındırma.",p:"Cilt temizlenir."},
   {m:"kubbe",k:"Koltukta",h:"Dermabrazyon ve ışık.",p:"Dermabrazyon uygulamasının ardından LED ile tamamlanır."},
   {m:"led",k:"Sonra",h:"Daha pürüzsüz bir yüzey.",p:"Ana bakımların 5 seanslık paketleri vardır; uzmanımız önerir."}],
 faq:[["Ne kadar sürer?","90 dakika."]],
 route:["hydra-elite","cilt-yenileme","klasik-cilt-bakimi"],shoot:true},
"hydra-elite":{t:"Hydra elite nem bakımı",code:"chydra",kind:"I",grp:"isilti",h1:["Hydra elite","nem bakımı"],
 lede:"Susuz cilt için nem odaklı yol.",hero:"kopuk",heroNote:"Temizleme köpüğü, salonumuzda çekildi. Hydra uygulamasının çekimi hazırlanıyor.",
 acts:[{m:"analiz",k:"Aynada",h:"Gerilen, pul pul olan cilt.",p:"Nem eksikliği makyajı da cildi de yorgun gösterir."},
   {m:"kopuk",k:"Yol",h:"Nem için doğru bakım.",p:"İhtiyacınıza göre dermabrazyon ya da Paris ışıltısı önerilir."},
   {m:"led",k:"Sonra",h:"Rahatlamış cilt.",p:"Bakım ışıkla tamamlanır."}],
 faq:[["Hydra elite'in fiyatı ne?","Nem bakımı bir ihtiyaç başlığıdır; uygulanacak bakımın fiyatı kendi sayfasında."]],
 route:["dermabrazyon","paris-isiltisi-bakimi"],shoot:true},
"hassas-cilt":{t:"Hassas cilt bakımı",code:"chassas",kind:"I",grp:"akne",h1:["Hassas cilt","bakımı"],
 lede:"Çabuk kızaran cilt için nazik bir yol.",hero:"led",heroNote:"LED ışık terapisi, salonumuzda çekildi.",
 acts:[{m:"analiz",k:"Aynada",h:"Kızarıklık, yanma, gerginlik.",p:"Hassas cilt her ürüne tepki verir. Önce neye tepki verdiğini anlarız."},
   {m:"kopuk",k:"Yol",h:"Nazik temizlik.",p:"Yumuşak arındırma ve sade adımlarla başlarız."},
   {m:"led",k:"Işık",h:"Yatıştırıcı kapanış.",p:"LED ışık terapisi sakin bir kapanış sağlar."}],
 faq:[["Hassas cildim var, hangi bakımla başlamalıyım?","Genellikle cilt temizliği ya da klasik bakımla başlarız; uzmanımız cildinize bakarak karar verir."]],
 route:["cilt-temizligi","klasik-cilt-bakimi"],shoot:true},
"antioksidan-bakimi":{t:"Antioksidan bakımı",code:"canti",kind:"I",grp:"isilti",h1:["Antioksidan","bakımı"],
 lede:"Şehir, güneş ve stres yorgunluğuna karşı canlandırıcı yol.",hero:"masaj",heroNote:"Yüz masajı, salonumuzda çekildi. Serum uygulamasının çekimi hazırlanıyor.",
 acts:[{m:"analiz",k:"Aynada",h:"Gri, yorgun bir ton.",p:"Şehir hayatı cildin canlılığını azaltır."},
   {m:"masaj",k:"Yol",h:"Canlandırıcı bakımlar.",p:"Paris ışıltısı ve Hollywood bakımı bu ihtiyaca en yakın bakımlarımızdır."},
   {m:"led",k:"Sonra",h:"Daha canlı görünüm.",p:"LED ile kapanış."}],
 route:["paris-isiltisi-bakimi","hollywood-bakimi","klasik-cilt-bakimi"],shoot:true},
"dudak-bakimi":{t:"Dudak bakımı",code:"cdudak",kind:"H",opt:"dudak",from:1000,grp:"vucut",h1:["Dudak","bakımı"],
 lede:"Kuru, pürüzlü dudaklara yumuşaklık.",hero:"type:dudak",heroNote:"Dudak bakımına özel çekimimiz hazırlanıyor.",
 acts:[{m:"analiz",k:"Aynada",h:"Çatlayan, pul pul dudaklar.",p:"Soğuk, rüzgâr ve susuzluk en çok dudakları etkiler."},
   {m:"masaj",k:"Koltukta",h:"Peeling ve maske.",p:"Dudaklar nazikçe arındırılır ve beslenir."},
   {m:"led",k:"Sonra",h:"Yumuşak görünüm.",p:"Dudak bakımı 3 seviyede ve 3 seanslık paketlerle sunulur."}],
 levels:"1.000 · 1.500 · 2.000 TL (3 seviye)",
 faq:[["Kalıcı makyajla ilgisi var mı?","Hayır. Dudak bakımı bir cilt bakımıdır; renklendirme yapılmaz."]],
 route:["klasik-cilt-bakimi"],shoot:true},
"cilt-inceltme":{t:"Sıkı görünüm bakımı",code:"csiki",kind:"I",grp:"yas",h1:["Sıkı görünüm","bakımı"],
 lede:"Gevşek görünen yüz hattı için doğru yol.",hero:"saten",heroNote:"Saten yüz germe başlığı, salonumuzda çekildi.",
 film:{k:"Seansın içinden",h:"Saten yüz germe nasıl uygulanır?",p:"Aşağı kaydırın: tek bir seanstan kesitler."},
 acts:[{m:"satenY",k:"Aynada",h:"Çene hattı eskisi gibi değil.",p:"Zamanla yüz hattı yumuşar."},
   {m:"saten",k:"Yol 1",h:"Saten yüz germe.",p:"Isıtan başlıkla 60 dakikalık sıkı görünüm bakımı."},
   {m:"kubbe",k:"Yol 2",h:"Cilt yenileme.",p:"Ton ve doku için bölgesel yenileme."}],
 route:["saten-yuz-germe","cilt-yenileme","anti-aging-bakimi"]},
"cilt-kararma-bakimi":{t:"Kararma görünümü bakımı",code:"ckarar",kind:"I",grp:"ton",h1:["Kararma görünümü","bakımı"],
 lede:"Koyulaşan bölgeler için önce doğru tanı, sonra doğru bakım.",hero:"led",heroNote:"LED ışık terapisi, salonumuzda çekildi. Bölgesel çekimimiz hazırlanıyor.",
 acts:[{m:"analiz",k:"Aynada",h:"Çene, boyun ya da dirsekte koyulaşma.",p:"Kararma görünümünün nedeni farklı olabilir; önce bölgeye bakarız."},
   {m:"kopuk",k:"Yol",h:"Ton ve leke bakımları.",p:"Bölgeye göre ton eşitleme ya da leke bakımı önerilir."},
   {m:"led",k:"Sonra",h:"Düzenli bakım ve koruma.",p:"Sonuç kişiye göre değişir; güneş koruması önemlidir."}],
 route:["ton-esitleme","leke-bakimi","dirsek-bakimi"],shoot:true},
"sirt-bakimi":{t:"Sırt bakımı",code:"csirt",kind:"H",opt:"sirt",from:3500,grp:"vucut",h1:["Sırt","bakımı"],
 lede:"Görmediğiniz ama hissettiğiniz bölge için.",hero:"type:Sırt",heroNote:"Sırt bakımına özel çekimimiz hazırlanıyor; sahte ya da başka salona ait görsel kullanmıyoruz.",
 acts:[{m:"analiz",k:"Aynada",h:"Sırtta sivilce ve siyah nokta.",p:"Sırt, kendi başınıza bakamadığınız bölgedir."},
   {m:"kopuk",k:"Koltukta",h:"Arındırma ve bakım.",p:"Sırt yüz bakımına benzer adımlarla temizlenir."},
   {m:"led",k:"Sonra",h:"Rahat bir sırt.",p:"Seans sayısı uzmanımızın önerisiyle belirlenir."}],
 pick:{h:"Hangi bölge?",o:[["yarim","Yarım sırt",""],["tam","Tam sırt",""],["emin","Emin değilim",""]],note:"Sırt bakımı bölgeye göre 3.500 TL'den başlar (randevu sistemimizdeki menü). Kesin fiyatı bölgenize göre iletiriz.",msg:"Merhaba, sırt bakımı ({x}) için fiyat ve uygun saat öğrenebilir miyim?"},
 route:["koltuk-alti-bakimi","akne-bakimi"],shoot:true},
"koltuk-alti-bakimi":{t:"Koltuk altı bakımı",code:"ckoltuk",kind:"H",opt:"koltuk",grp:"vucut",h1:["Koltuk altı","bakımı"],
 lede:"Yarım saatlik bölgesel bakım.",hero:"type:Koltuk altı",heroNote:"Bölgesel çekimimiz hazırlanıyor; sahte ya da başka salona ait görsel kullanmıyoruz.",
 acts:[{m:"analiz",k:"Aynada",h:"Koyulaşma ve pürüz.",p:"Tıraş ve sürtünme bu bölgede ton farkı bırakabilir."},
   {m:"kopuk",k:"Koltukta",h:"Arındırma ve bakım.",p:"Bölge temizlenir ve bakımla tamamlanır."},
   {m:"led",k:"Sonra",h:"Düzenli bakım.",p:"Seans sayısını uzmanımız önerir."}],
 route:["sirt-bakimi","dirsek-bakimi","cilt-kararma-bakimi"],shoot:true},
"dirsek-bakimi":{t:"Dirsek bakımı",code:"cdirsek",kind:"I",grp:"vucut",h1:["Dirsek","bakımı"],
 lede:"Koyu ve kuru dirsekler için doğru yol.",hero:"type:Dirsek",heroNote:"Bölgesel çekimimiz hazırlanıyor; sahte ya da başka salona ait görsel kullanmıyoruz.",
 acts:[{m:"analiz",k:"Aynada",h:"Kuru, koyu, pürüzlü.",p:"Dirsek yaslanmaktan ve kuruluktan en çok etkilenen bölgedir."},
   {m:"kopuk",k:"Yol",h:"Bölgesel bakım.",p:"İhtiyaca göre ton eşitleme ya da kararma görünümü bakımı önerilir."},
   {m:"led",k:"Sonra",h:"Düzenli bakım.",p:"Evde nemlendirme önemlidir."}],
 route:["ton-esitleme","cilt-kararma-bakimi","koltuk-alti-bakimi"],shoot:true}
};
