# -*- coding: utf-8 -*-
"""Cilt Atlası content: 25 pages (hub + 24) as data.  Facts only from the CRM menu (10-07) and what the salon's own
media shows.  Types: H = has its own CRM item (price shown); İ = a need guide (no price of its own; it points to real
treatments and shows THEIR prices as theirs); hub.  status: tam = real result proof · ince = weak · cekim = stand-in
until the staff shoot (manifest_cilt.json "cekim").  No promises: "görünüm", never "kesin", "kalıcı", "%".
"""

M = "m/ig/"

# CRM menu (cilt, 2026-10-07): id -> (name, price, minutes).  5-session packages = 4.5 x single (ana bakımlar)
MENU = {
    "temizlik": ("Cilt temizliği", 1000, 30), "mini": ("Mini cilt bakımı", 1500, 60), "klasik": ("Klasik cilt bakımı", 2000, 90),
    "paris": ("Paris ışıltısı", 4500, 120), "akne": ("Akne bakımı", 5000, 120), "hollywood": ("Hollywood bakımı", 5500, 120),
    "leke": ("Leke bakımı", 5500, 120), "yenileme": ("Cilt yenileme bakımı", 6000, 120), "derma": ("Dermabrazyon yüz bakımı", 6500, 90),
    "saten": ("Saten yüz germe", 4500, 60), "ton": ("Ton eşitleme", 4500, None), "dudak": ("Dudak bakımı", 1000, None),
    "sirt": ("Sırt bakımı", 3500, None), "koltuk": ("Koltuk altı bakımı", 4500, 30),
}
PACKAGE = {"paris", "akne", "hollywood", "leke", "yenileme", "derma"}
MENU_GROUPS = [
    ("Ara bakım", ["temizlik", "mini", "klasik"]),
    ("Ana bakım · 5 seans paket seçeneği", ["paris", "akne", "hollywood", "leke", "yenileme", "derma"]),
    ("Yüz germe ve ton", ["saten", "ton"]),
    ("Bölgesel", ["dudak", "sirt", "koltuk"]),
]
FROM = {"ton": "4.500–6.500 TL · alan boyuna göre", "dudak": "1.000–2.000 TL · 3 seanslık paketler", "sirt": "3.500–7.000 TL · üç seçenek"}

# need groups for the atlas map on the hub
GROUPS = [
    ("Temizlik ve akne", ["cilt-temizligi", "klasik-cilt-bakimi", "akne-bakimi", "hassas-cilt"]),
    ("Işıltı ve nem", ["hollywood-bakimi", "paris-isiltisi-bakimi", "dermabrazyon", "hydra-elite", "antioksidan-bakimi"]),
    ("Ton ve leke", ["ton-esitleme", "leke-bakimi", "cilt-kararma-bakimi", "cilt-yenileme"]),
    ("Sıkılık ve yıllar", ["saten-yuz-germe", "anti-aging-bakimi", "cilt-inceltme", "goz-cevresi-bakimi"]),
    ("Önce bakalım", ["cilt-analizi", "yuz-bakimi", "cilt-bakimi-fiyatlari"]),
    ("Yüz dışı bölgeler", ["dudak-bakimi", "sirt-bakimi", "koltuk-alti-bakimi", "dirsek-bakimi"]),
]

HOW = {
    "H": [("Cildinize bakarız", "Cilt tipiniz, hassasiyetiniz ve şikâyetiniz birlikte değerlendirilir."),
          ("Bakımı uygularız", "Seçilen bakımın adımları sırayla; süre menüde yazdığı kadar."),
          ("Takibi planlarız", "Sonraki seansın gerekip gerekmediğini uzmanınız cildinize bakarak söyler.")],
    "İ": [("Önce görüşürüz", "Şikâyetinizi ve cildinizi birlikte değerlendiririz."),
          ("Bakımı seçeriz", "Bu ihtiyaç için uygun bakım, menüdeki gerçek bakımlar arasından önerilir."),
          ("Takip ederiz", "Cildinizin yanıtına göre sonraki adım birlikte planlanır.")],
}

# page data -------------------------------------------------------------------------------------------------------
# hero: {"pair": slug, "size": n} | {"video": slug} | {"img": file} | {"type": "dudak"|"sirt"|"goz"}
P = {
 "cilt-bakimi-fiyatlari": dict(t="Cilt bakımı fiyatları", h1="Cilt Bakımı <em>Fiyatları</em> Ankara", type="hub", status="tam",
     lede="Menüdeki her bakım, süresi ve fiyatıyla.", hero={"img": "m/walk-09.webp", "alt": "Salonumuzun cilt bakım odası: büyüteç lambası ve bakım yatağı"},
     scene="menu", chip="1.000 TL'den", bar="Cilt bakımı",
     faq=[("5 seanslık paket nasıl hesaplanıyor?", "Ana bakımlarda 5 seanslık paket, tek seans fiyatının 4,5 katıdır: beş seans, dört buçuk seans fiyatına."),
          ("Fiyata neler dahil?", "Menüde yazan süre boyunca seçilen bakımın bütün adımları. Ek bir işlem gerekirse önceden söylenir.")],
     cekim="Geniş açı oda çekimi (P3)"),
 "klasik-cilt-bakimi": dict(t="Klasik cilt bakımı", h1="Klasik Cilt <em>Bakımı</em>", type="H", opt="klasik", status="tam",
     lede="90 dakika: analizden LED ışığa kadar, adım adım.", hero={"video": "cilt-led-kubbe"}, scene="timeline",
     timeline=[("Analiz", "Büyüteç lambası altında cildinize bakılır.", {"video": "cilt-analiz"}),
               ("Temizlik", "Altın lavabo, ılık su ve süngerle yüz temizlenir.", {"video": "cilt-sunger"}),
               ("Detaylı temizlik", "Siyah noktalar özenle temizlenir.", {"video": "cilt-komedon"}),
               ("Maske", "Cildinize uygun maske kâsede hazırlanıp sürülür.", {"video": "cilt-maske"}),
               ("LED ışık", "Bakım LED kubbe altında tamamlanır.", {"img": M + "cilt-led-mavi-720.webp"})],
     gallery=[("pair", "akne-b", "Akne görünümlü ciltte bakım sonrası")],
     faq=[("İlk kez yaptıracağım, bununla mı başlamalıyım?", "Çoğu danışanımız klasik cilt bakımıyla başlar. İhtiyacınızı ön görüşmede birlikte netleştiririz."),
          ("Ne sıklıkla yaptırmalıyım?", "Cildinize ve şikâyetinize göre değişir; uzmanınız seans sonunda önerir.")],
     note="Adımların sırası ve süresi cildinize göre değişebilir."),
 "cilt-temizligi": dict(t="Cilt temizliği", h1="Cilt <em>Temizliği</em>", type="H", opt="temizlik", status="ince",
     lede="Yarım saatte gözenek ve siyah nokta temizliği.", hero={"video": "cilt-komedon"}, scene="timeline",
     timeline=[("Hazırlık", "Cilt büyüteç lambası altında hazırlanır.", {"img": M + "cilt-lamba-720.webp"}),
               ("Temizlik", "Altın lavaboda süngerle temizlik.", {"video": "cilt-sunger"}),
               ("Detaylı temizlik", "Siyah noktalar tek tek temizlenir.", {"video": "cilt-komedon"})],
     faq=[("Temizlik sonrası kızarıklık olur mu?", "Detaylı temizlikten hemen sonra hafif kızarıklık görülebilir; genellikle kısa sürede geçer."),
          ("Klasik bakımdan farkı ne?", "Cilt temizliği 30 dakikalık bir ara bakımdır; klasik cilt bakımı 90 dakika sürer ve maske, LED gibi adımları da içerir.")],
     cekim="Burun gözenekleri önce/sonra yakın çekim"),
 "akne-bakimi": dict(t="Akne bakımı", h1="Akne <em>Bakımı</em> Ankara", type="H", opt="akne", status="tam",
     lede="İltihaplı, kızarık görünümden daha sakin bir cilde.", hero={"pair": "akne-a", "size": 1200}, scene="band",
     band={"video": "cilt-darsonval", "eyebrow": "Darsonval", "h": "Turuncu ışık, <em>sakin</em> cilt.", "p": "Akne bakımlarımızda kullandığımız darsonval uygulaması, salonumuzda çekildi."},
     gallery=[("pair", "akne-b", "Akne bakımı: yoğun sivilceden hafif kızarıklığa")],
     faq=[("Kaç seans gerekir?", "Cildinize ve akne görünümünün yoğunluğuna göre değişir. Ana bakımlarda 5 seanslık paket seçeneği var."),
          ("Bakım sonrası nelere dikkat etmeliyim?", "Uzmanınız seans sonunda cildinize göre kısa bir bakım önerisi verir.")],
     review="Berke S."),
 "cilt-yenileme": dict(t="Cilt yenileme", h1="Cilt <em>Yenileme</em> Bakımı", type="H", opt="yenileme", status="tam",
     lede="Mat ve yorgun görünümden daha canlı, eşit bir tona.", hero={"pair": "cilt-ters", "size": 480}, scene="picker",
     picker={"eyebrow": "Hücresel yenileme", "h": "Kaç <em>bölge</em>?", "p": "Hücresel yenileme bölge sayısına göre fiyatlanır.",
             "opts": [("1", "1 bölge", 3500), ("2", "2 bölge", 4000), ("3", "3 bölge", 6000)], "ref": "Hücresel yenileme"},
     faq=[("Cilt yenileme bakımı kaç dakika?", "Menüde 120 dakika."), ("Paket var mı?", "Evet, 5 seanslık paket seçeneği var; tek seans fiyatının 4,5 katı.")]),
 "ton-esitleme": dict(t="Ton eşitleme", h1="Ton <em>Eşitleme</em>", type="H", opt="ton", status="ince",
     lede="Kızarıklık ve ton farkı görünümünü dengelemek için.", hero={"pair": "cilt-ters", "size": 480}, scene="picker",
     picker={"eyebrow": "Alan boyu", "h": "Ne kadar <em>alan</em>?", "p": "Ton eşitleme, uygulanan alanın büyüklüğüne göre fiyatlanır.",
             "opts": [("kucuk", "Küçük alan", 4500), ("orta", "Orta alan", 5500), ("genis", "Geniş alan", 6500)], "ref": "Ton eşitleme"},
     pairnote="Bakım sonrası tonu daha eşit görünen bir danışanımız; fotoğraf salonumuzda çekildi.",
     faq=[("Hangi alan bana uygun?", "Alanı ön görüşmede cildinize bakarak birlikte belirleriz.")]),
 "saten-yuz-germe": dict(t="Saten yüz germe", h1="Saten Yüz <em>Germe</em>", type="H", opt="saten", status="tam",
     lede="Kaş ve göz çevresinden çene hattına, saten başlıkla.", hero={"video": "cilt-saten"}, scene="film",
     film={"set": "saten-film", "n": 45, "steps": [("01 · Ayar", "Ekranda bölge ve süre seçilir."), ("02 · Kaş ve göz", "Başlık kaş ve göz çevresinde gezinir."), ("03 · Yanak", "Yanak ve çene hattına iner.")]},
     gallery=[("img", M + "cilt-saten-ekran-720.webp", "Saten yüz germe cihazının ekranı")],
     faq=[("Ne kadar sürer?", "Menüde 60 dakika."), ("Kimler için uygun?", "Sıkılık görünümü için bakım isteyenler. Uygunluğu ön görüşmede değerlendiririz.")]),
 "anti-aging-bakimi": dict(t="Anti aging bakımı", h1="Anti Aging <em>Bakımı</em>", type="İ", status="ince",
     lede="Yıllara göre iki yol: sıkılık görünümü ya da yenileme.", hero={"video": "cilt-saten"}, scene="paths",
     paths=[("saten-yuz-germe", "Sıkılık görünümü için"), ("cilt-yenileme", "Matlık ve doku için"), ("cilt-analizi", "Emin değilseniz önce analiz")],
     faq=[("Anti aging için ayrı bir bakım var mı?", "Menüde ayrı bir 'anti aging' kalemi yok; ihtiyacınıza göre saten yüz germe ya da cilt yenileme önerilir.")],
     cekim="Göz çevresi ve şakak önce/sonra"),
 "goz-cevresi-bakimi": dict(t="Göz çevresi bakımı", h1="Göz Çevresi <em>Bakımı</em>", type="İ", status="cekim",
     lede="Göz çevresindeki yorgun görünüm için nazik bir yol.", hero={"type": "goz"}, scene="paths",
     paths=[("saten-yuz-germe", "Kaş ve göz çevresinde saten başlık"), ("klasik-cilt-bakimi", "Genel bakımla birlikte"), ("cilt-analizi", "Önce analiz")],
     faq=[("Göz çevresi için ayrı fiyat var mı?", "Menüde ayrı bir kalem yok; uygun bakımı ön görüşmede birlikte seçeriz.")],
     cekim="Göz çevresi önce/sonra (kaz ayağı, matlık)"),
 "cilt-analizi": dict(t="Cilt analizi", h1="Cilt <em>Analizi</em>", type="İ", status="tam",
     lede="Büyüteç altında cildinize birlikte bakalım; doğru bakım oradan çıkar.", hero={"video": "cilt-analiz"}, scene="facemap",
     faq=[("Analiz ücretli mi?", "Analiz, bakım öncesi ön görüşmenin parçasıdır; bakım randevusuyla birlikte yapılır."),
          ("Ne kadar sürer?", "Kısa bir değerlendirme; ardından size uygun bakım önerilir.")]),
 "yuz-bakimi": dict(t="Yüz bakımı", h1="Yüz <em>Bakımı</em> Ankara", type="İ", status="tam",
     lede="Yüzünüz için dört yol; hangisinin size uyduğunu birlikte seçelim.", hero={"pair": "cilt-ters", "size": 480}, scene="paths",
     paths=[("cilt-temizligi", "30 dakikada temizlik"), ("klasik-cilt-bakimi", "90 dakikalık klasik bakım"), ("hollywood-bakimi", "Işıltı için ana bakım"), ("akne-bakimi", "Akne görünümü için")],
     gallery=[("pair", "akne-a", "Akne bakımı sonrası")]),
 "leke-bakimi": dict(t="Leke bakımı", h1="Leke <em>Bakımı</em> Ankara", type="H", opt="leke", status="cekim",
     lede="Leke ve ton farkı görünümü için 120 dakikalık ana bakım.", hero={"img": "m/walk-09.webp", "alt": "Salonumuzun cilt bakım odası"}, scene="proof",
     proof={"pair": "cilt-ters", "size": 480, "label": "Ton eşitleme sonrası (leke bakımı değil)"},
     faq=[("Kaç seans gerekir?", "Leke görünümünün türüne ve cildinize göre değişir; 5 seanslık paket seçeneği var.")],
     cekim="P1 · leke yakın planı önce/sonra + uygulama klibi"),
 "hollywood-bakimi": dict(t="Hollywood bakımı", h1="Hollywood <em>Bakımı</em>", type="H", opt="hollywood", status="cekim",
     lede="Özel günden önce ışıltılı bir cilt görünümü için.", hero={"video": "cilt-led-kubbe"}, scene="duel",
     faq=[("Paris ışıltısından farkı ne?", "İkisi de 120 dakikalık ana bakımdır; içerik ve adım farkını ön görüşmede uzmanımız anlatır.")],
     cekim="P1 · maske + LED klibi; yandan ışıkla ışıltı sonrası yanak"),
 "paris-isiltisi-bakimi": dict(t="Paris ışıltısı", h1="Paris <em>Işıltısı</em> Bakımı", type="H", opt="paris", status="cekim",
     lede="Mat görünüme ışıltı; 120 dakikalık ana bakım.", hero={"img": M + "cilt-cihaz-720.webp", "alt": "Salonumuzdaki çok başlıklı cilt bakım cihazı"}, scene="duel",
     faq=[("Hollywood bakımından farkı ne?", "İkisi de 120 dakikalık ana bakımdır; içerik ve adım farkını ön görüşmede uzmanımız anlatır.")],
     cekim="P1 · maske + LED klibi; yandan ışıkla ışıltı sonrası yanak"),
 "dermabrazyon": dict(t="Dermabrazyon", h1="Dermabrazyon <em>Yüz Bakımı</em>", type="H", opt="derma", status="cekim",
     lede="Çok başlıklı cihazımızla 90 dakikalık bakım.", hero={"img": M + "cilt-cihaz-720.webp", "alt": "Salonumuzdaki 8 başlıklı cilt bakım cihazı"}, scene="heads",
     gallery=[("video", "cilt-hydra", "Başlıkla uygulama, salonumuzda")],
     faq=[("Hangi başlık kullanılıyor?", "Başlıklar cildinize göre seçilir; uzmanınız seans sırasında gösterir.")],
     cekim="P1 · başlık çalışırken 10 sn (su ve vakum), tankta toplanan kir"),
 "hydra-elite": dict(t="Hydra elite nem bakımı", h1="Hydra Elite <em>Nem</em> Bakımı", type="İ", status="ince",
     lede="Nem ihtiyacı için başlıklı bakım; uygun kalemi birlikte seçelim.", hero={"video": "cilt-hydra"}, scene="heads",
     paths=[("dermabrazyon", "Başlıklı yüz bakımı"), ("paris-isiltisi-bakimi", "Işıltı için"), ("klasik-cilt-bakimi", "Genel bakım")],
     faq=[("Hydra elite menüde hangi bakım?", "Menüde ayrı bir 'hydra elite' kalemi yok; nem ihtiyacınız için uygun bakımı ön görüşmede seçeriz.")],
     cekim="P1 · başlık çalışırken su ve vakum görünsün"),
 "hassas-cilt": dict(t="Hassas cilt bakımı", h1="Hassas Cilt <em>Bakımı</em>", type="İ", status="ince",
     lede="Kızarmaya yatkın ciltler için nazik bir başlangıç.", hero={"img": M + "cilt-kirmizi-led-720.webp", "alt": "Karanlık odada kırmızı ışıklı uygulama"}, scene="paths",
     paths=[("cilt-temizligi", "Nazik temizlikle başlayın"), ("klasik-cilt-bakimi", "Sonra klasik bakım"), ("cilt-analizi", "Önce birlikte bakalım")],
     faq=[("Hassas cildim var, ne söylemeliyim?", "Bildiğiniz hassasiyetleri ön görüşmede söyleyin; bakım buna göre seçilir.")],
     cekim="P2 · kırmızı LED altında sakin cilt"),
 "antioksidan-bakimi": dict(t="Antioksidan bakımı", h1="Antioksidan <em>Bakımı</em>", type="İ", status="cekim",
     lede="Serum ve maskeyle cildi besleyen bakımlar için rehber.", hero={"img": M + "cilt-urun-720.webp", "alt": "Salonda kullanılan bakım ürünü"}, scene="paths",
     paths=[("klasik-cilt-bakimi", "Maske adımıyla klasik bakım"), ("paris-isiltisi-bakimi", "Işıltı için ana bakım")],
     faq=[("Hangi ürünler kullanılıyor?", "Salonda kullandığımız profesyonel ürünleri ön görüşmede gösteririz.")],
     cekim="P2 · serum ve ampul uygulama yakın planı"),
 "dudak-bakimi": dict(t="Dudak bakımı", h1="Dudak <em>Bakımı</em>", type="H", opt="dudak", status="cekim",
     lede="Kuru, pürüzlü dudaklar için üç seviye.", hero={"type": "dudak"}, scene="picker",
     picker={"eyebrow": "Üç seviye", "h": "3 seanslık <em>paketler</em>", "p": "Dudak bakımı 3 seanslık paketler halinde; içeriği seviyeye göre ön görüşmede anlatılır.",
             "opts": [("1", "1. seviye", 1000), ("2", "2. seviye", 1500), ("3", "3. seviye", 2000)], "ref": "Dudak bakımı"},
     faq=[("Kalıcı dudak renklendirmeyle aynı mı?", "Hayır. Dudak bakımı bir bakım hizmetidir; kalıcı renk için kalıcı makyaj sayfamıza bakın.")],
     cekim="P2 · dudak maske ve peeling önce/sonra"),
 "cilt-inceltme": dict(t="Sıkı görünüm bakımı", h1="Sıkı Görünüm <em>Bakımı</em>", type="İ", status="tam",
     lede="Sarkma görünümü için iki gerçek yol.", hero={"video": "cilt-saten"}, scene="paths",
     paths=[("saten-yuz-germe", "Saten başlıkla yüz germe"), ("cilt-yenileme", "Hücresel yenileme")],
     faq=[("Ayrı bir fiyatı var mı?", "Menüde ayrı bir kalem yok; saten yüz germe ya da cilt yenileme önerilir.")]),
 "cilt-kararma-bakimi": dict(t="Kararma görünümü bakımı", h1="Kararma <em>Görünümü</em> Bakımı", type="İ", status="cekim",
     lede="Ton farkı görünümü için doğru bakımı birlikte seçelim.", hero={"img": M + "cilt-urun-720.webp", "alt": "Salonda kullanılan bakım ürünü"}, scene="paths",
     paths=[("ton-esitleme", "Alan boyuna göre ton eşitleme"), ("leke-bakimi", "Leke görünümü için ana bakım"), ("cilt-analizi", "Önce analiz")],
     faq=[("Hangi bölgelere uygulanır?", "Bölgeyi ve uygun bakımı ön görüşmede birlikte belirleriz.")],
     cekim="P2 · bölge önce/sonra (rızalı)"),
 "sirt-bakimi": dict(t="Sırt bakımı", h1="Sırt <em>Bakımı</em>", type="H", opt="sirt", status="cekim",
     lede="Sırttaki sivilce ve siyah nokta görünümü için.", hero={"type": "sirt"}, scene="picker",
     picker={"eyebrow": "Bölge", "h": "Yarım mı, <em>tam</em> mı?", "p": "Menüde sırt için 3.500 – 7.000 TL arası üç seçenek var; hangisinin uygun olduğunu sırtınıza bakarak söyleriz.",
             "opts": [("yarim", "Yarım sırt", 3500), ("tam", "Tam sırt", 6500)], "ref": "Sırt bakımı", "from": True},
     faq=[("Ne kadar sürer?", "Seçilen bölgeye göre değişir; randevuda netleştiririz.")],
     cekim="P2 · bölge önce/sonra (rızalı) + uygulama eli"),
 "koltuk-alti-bakimi": dict(t="Koltuk altı bakımı", h1="Koltuk Altı <em>Bakımı</em>", type="H", opt="koltuk", status="cekim",
     lede="Ton farkı ve pürüz görünümü için 30 dakika.", hero={"img": "m/walk-09.webp", "alt": "Salonumuzun cilt bakım odası"}, scene="paths",
     paths=[("cilt-kararma-bakimi", "Kararma görünümü rehberi"), ("ton-esitleme", "Ton eşitleme")],
     faq=[("Lazer epilasyonla aynı gün olur mu?", "Uygunluğu uzmanınız iki işlemin sırasına bakarak söyler.")],
     cekim="P2 · bölge önce/sonra (rızalı)"),
 "dirsek-bakimi": dict(t="Dirsek bakımı", h1="Dirsek <em>Bakımı</em>", type="İ", status="cekim",
     lede="Dirsekteki koyu ve kuru görünüm için rehber.", hero={"img": "m/walk-09.webp", "alt": "Salonumuzun cilt bakım odası"}, scene="paths",
     paths=[("cilt-kararma-bakimi", "Kararma görünümü rehberi"), ("ton-esitleme", "Ton eşitleme")],
     faq=[("Dirsek için ayrı fiyat var mı?", "Menüde ayrı bir kalem yok; uygun bakımı ön görüşmede seçeriz.")],
     cekim="P2 · bölge önce/sonra (rızalı)"),
}
for _k, _v in P.items():
    _v.setdefault("gallery", [])
    _v.setdefault("faq", [])

THUMB = {  # atlas tiles: one real image per page (stand-ins are the room, device or product)
    "cilt-bakimi-fiyatlari": "m/walk-09.webp", "klasik-cilt-bakimi": M + "cilt-led-kubbe-poster.webp", "cilt-temizligi": M + "cilt-komedon-poster.webp",
    "akne-bakimi": M + "akne-a-sonra-800.webp", "cilt-yenileme": M + "cilt-ters-sonra-480.webp", "ton-esitleme": M + "cilt-ters-sonra-480.webp",
    "saten-yuz-germe": M + "cilt-saten-poster.webp", "anti-aging-bakimi": M + "cilt-saten-poster.webp", "goz-cevresi-bakimi": M + "cilt-saten-poster.webp",
    "cilt-analizi": M + "cilt-analiz-poster.webp", "yuz-bakimi": M + "cilt-ters-sonra-480.webp", "leke-bakimi": "m/walk-09.webp",
    "hollywood-bakimi": M + "cilt-led-kubbe-poster.webp", "paris-isiltisi-bakimi": M + "cilt-cihaz-720.webp", "dermabrazyon": M + "cilt-cihaz-720.webp",
    "hydra-elite": M + "cilt-hydra-poster.webp", "hassas-cilt": M + "cilt-kirmizi-led-720.webp", "antioksidan-bakimi": M + "cilt-urun-720.webp",
    "dudak-bakimi": M + "cilt-hazirlik-720.webp", "cilt-inceltme": M + "cilt-saten-poster.webp", "cilt-kararma-bakimi": M + "cilt-urun-720.webp",
    "sirt-bakimi": M + "cilt-sunger-poster.webp", "koltuk-alti-bakimi": "m/walk-09.webp", "dirsek-bakimi": M + "cilt-sunger-poster.webp",
}
